/**
 * ============================================================================
 *  OWNER: PERSON A
 *  Everyone else: do not edit this file.
 * ============================================================================
 *
 * This is the gatekeeper.
 * If this script does not hit the targets below, the engine is not ready.
 *
 * TARGETS:
 *   - JPEG q90: ≥ 47/48
 *   - JPEG q75: ≥ 46/48
 *   - JPEG q60: ≥ 44/48
 *   - JPEG q45: ≥ 41/48
 *   - Resize 50% -> 100%: ≥ 43/48
 *   - Crop 20%: ≥ 40/48
 *   - Noise (Gaussian): ≥ 42/48
 *   - Screenshot (Resize + JPEG + Brightness): ≥ 40/48
 *
 * Run with: npm run attack:suite
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import { fileURLToPath } from 'node:url';
import { embed, extract } from '../server/core/watermark.js';
import { buildPayload } from '../server/core/payload.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, 'metrics.json');
const FIXTURE_PATH = path.join(__dirname, 'fixtures', 'sample.png');

const ATTACKS = [
  { id: 'jpeg_q90', name: 'JPEG q90', target: 48 },
  { id: 'jpeg_q75', name: 'JPEG q75', target: 46 },
  { id: 'jpeg_q60', name: 'JPEG q60', target: 44 },
  { id: 'jpeg_q45', name: 'JPEG q45', target: 41 },
  { id: 'resize_50', name: 'Resize 50%', target: 43 },
  { id: 'crop_20', name: 'Crop 20%', target: 40 },
  { id: 'noise', name: 'Gaussian noise', target: 42 },
  { id: 'screenshot', name: 'Screenshot sim', target: 40 },
];
const DELTAS = [4, 8, 12, 16, 24];

async function ensureFixture() {
  try {
    await fs.mkdir(path.dirname(FIXTURE_PATH), { recursive: true });
    await fs.access(FIXTURE_PATH);
  } catch {
    await sharp({
      create: { width: 512, height: 512, channels: 3, background: { r: 128, g: 128, b: 128 } },
    })
      .png()
      .toFile(FIXTURE_PATH);
  }
}

function bitsMatching(a, b) {
  let count = 0;
  for (let i = 0; i < 48; i++) {
    if (a[i] === b[i]) count++;
  }
  return count;
}

async function applyAttack(buffer, attackId) {
  const image = sharp(buffer);
  const meta = await image.metadata();
  switch (attackId) {
    case 'jpeg_q90':
      return image.jpeg({ quality: 90 }).toBuffer();
    case 'jpeg_q75':
      return image.jpeg({ quality: 75 }).toBuffer();
    case 'jpeg_q60':
      return image.jpeg({ quality: 60 }).toBuffer();
    case 'jpeg_q45':
      return image.jpeg({ quality: 45 }).toBuffer();
    case 'resize_50':
      return image
        .resize(Math.round(meta.width * 0.5))
        .toBuffer()
        .then((buf) => sharp(buf).resize(meta.width, meta.height).toBuffer());
    case 'crop_20':
      return image
        .extract({
          left: Math.round(meta.width * 0.1),
          top: Math.round(meta.height * 0.1),
          width: Math.round(meta.width * 0.8),
          height: Math.round(meta.height * 0.8),
        })
        .toBuffer()
        .then((buf) => sharp(buf).resize(meta.width, meta.height).toBuffer());
    case 'noise':
      return image.blur(1.5).toBuffer();
    case 'screenshot':
      return image
        .resize(Math.round(meta.width * 0.8))
        .jpeg({ quality: 70 })
        .modulate({ brightness: 1.2 })
        .toBuffer()
        .then((buf) => sharp(buf).resize(meta.width, meta.height).toBuffer());
    default:
      return buffer;
  }
}

async function main() {
  console.log('\n  Attack suite — SIH26237\n');
  await ensureFixture();
  const origBuffer = await fs.readFile(FIXTURE_PATH);
  const payloadBits = buildPayload(1, 1698765432);

  console.log('  Running attacks (DELTA=12)...');
  const d = 12;
  const { buffer: markedBuffer, psnrDb: basePsnr } = await embed(origBuffer, payloadBits, d);

  const results = [];
  for (const a of ATTACKS) {
    const attacked = await applyAttack(markedBuffer, a.id);
    const { payloadBits: recovered } = await extract(attacked);
    const matched = bitsMatching(payloadBits, recovered);
    const survived = matched >= a.target;
    console.log(
      `    ${a.name.padEnd(16)}: ${matched}/48 ${survived ? '✅' : '❌'} (target: ${a.target})`
    );
    results.push({
      name: a.name,
      survived,
      bitsRecovered: matched,
      psnrDb: basePsnr,
      target: a.target,
    });
  }

  console.log('\n  Delta sweep (JPEG q75)...');
  const curve = [];
  for (const d of DELTAS) {
    const { buffer: dMarked, psnrDb } = await embed(origBuffer, payloadBits, d);
    const attacked = await applyAttack(dMarked, 'jpeg_q75');
    const { payloadBits: dRecovered } = await extract(attacked, d);
    const matched = bitsMatching(payloadBits, dRecovered);
    console.log(
      `    DELTA ${String(d).padEnd(2)} -> PSNR: ${psnrDb.toFixed(2)} dB, Bits: ${matched}/48`
    );
    curve.push({ delta: d, psnrDb, bitsRecovered: matched });
  }

  const metrics = {
    source: 'attack-suite',
    generatedAt: new Date().toISOString(),
    attacks: results,
    psnrCurve: curve,
  };

  await fs.writeFile(OUT, JSON.stringify(metrics, null, 2));
  console.log(`\n  Wrote metrics to ${path.relative(process.cwd(), OUT)}\n`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
