/**
 * ============================================================================
 *  OWNER: PERSON A
 *  Everyone else: do not edit this file.
 * ============================================================================
 *
 * Turns raw signals into a number, a band, and — most importantly — sentences.
 *
 *   score = 0.45 * bitAgreement          // fraction of 48 bits recovered cleanly
 *         + 0.25 * (1 - pHashDist/64)
 *         + 0.15 * (1 - dHashDist/64)
 *         + 0.10 * (1 - aHashDist/64)
 *         + 0.05 * (chainVerified ? 1 : 0);
 *
 *   score >= 0.85 -> ATTRIBUTED     // name the person
 *   score >= 0.60 -> PROBABLE       // "investigate further"
 *   else          -> INCONCLUSIVE   // say "pata nahi" out loud
 *
 * Never return a name from here. Three bands, always: a wrong attribution is
 * the expensive failure in this system, so below 60% it reports that it does
 * not know rather than guessing.
 *
 * Always populate reasons[] with plain sentences — they are what makes a score
 * reviewable. Good: "46/48 watermark bits recovered (2 fixed by Reed-Solomon)".
 * Bad: "bitConfidence=0.958".
 */

import { notImplemented } from '../lib/errors.js';

export const WEIGHTS = {
  bitAgreement: 0.45,
  pHash: 0.25,
  dHash: 0.15,
  aHash: 0.1,
  chain: 0.05,
};

export const BANDS = { ATTRIBUTED: 0.85, PROBABLE: 0.6 };

/**
 * @param {{ bitConfidence:number, pHashDist:number, dHashDist:number,
 *           aHashDist:number, chainVerified:boolean }} sig
 * @returns {{ score:number, verdict:'ATTRIBUTED'|'PROBABLE'|'INCONCLUSIVE',
 *             reasons:string[] }}
 */
export function score(sig) {
  // TODO(A): implement the formula above verbatim, then tune the weights
  //          against test/attack-suite.js output. Build reasons[] as you go.
  throw notImplemented('confidence.score');
}

/** Map a raw score to its band. Kept separate so tests can reuse it. */
export function verdictFor(value) {
  if (value >= BANDS.ATTRIBUTED) return 'ATTRIBUTED';
  if (value >= BANDS.PROBABLE) return 'PROBABLE';
  return 'INCONCLUSIVE';
}
