/**
 * ============================================================================
 *  OWNER: PERSON A
 *  Everyone else: do not edit this file.
 * ============================================================================
 *
 * Turns raw signals into a number, a band, and — most importantly — sentences.
 *
 *   score = 0.45 * bitAgreement          // fraction of 48 bits recovered cleanly
 *         + 0.25 * (1 - pHashDist/64)
 *         + 0.15 * (1 - dHashDist/64)
 *         + 0.10 * (1 - aHashDist/64)
 *         + 0.05 * (chainVerified ? 1 : 0);
 *
 *   score >= 0.85 -> ATTRIBUTED     // name the person
 *   score >= 0.60 -> PROBABLE       // "investigate further"
 *   else          -> INCONCLUSIVE   // say "pata nahi" out loud
 *
 * Never return a name from here. Three bands, always: a wrong attribution is
 * the expensive failure in this system, so below 60% it reports that it does
 * not know rather than guessing.
 *
 * Always populate reasons[] with plain sentences — they are what makes a score
 * reviewable. Good: "46/48 watermark bits recovered (2 fixed by Reed-Solomon)".
 * Bad: "bitConfidence=0.958".
 */

export const WEIGHTS = {
  bitAgreement: 0.45,
  pHash: 0.25,
  dHash: 0.15,
  aHash: 0.1,
  chain: 0.05,
};

export const BANDS = { ATTRIBUTED: 0.85, PROBABLE: 0.6 };

/**
 * @param {{ bitConfidence:number, pHashDist:number, dHashDist:number,
 *           aHashDist:number, chainVerified:boolean }} sig
 * @returns {{ score:number, verdict:'ATTRIBUTED'|'PROBABLE'|'INCONCLUSIVE',
 *             reasons:string[] }}
 */
export function score(sig) {
  const {
    bitConfidence = 0,
    pHashDist = 64,
    dHashDist = 64,
    aHashDist = 64,
    chainVerified = false,
  } = sig;

  const scoreValue =
    WEIGHTS.bitAgreement * bitConfidence +
    WEIGHTS.pHash * (1 - pHashDist / 64) +
    WEIGHTS.dHash * (1 - dHashDist / 64) +
    WEIGHTS.aHash * (1 - aHashDist / 64) +
    WEIGHTS.chain * (chainVerified ? 1 : 0);

  const verdict = verdictFor(scoreValue);
  const reasons = [];

  // dHash reasoning
  if (dHashDist <= 8) reasons.push(`dHash distance ${dHashDist}/64 — strong visual match`);
  else if (dHashDist <= 16) reasons.push(`dHash distance ${dHashDist}/64 — moderate visual match`);
  else reasons.push(`dHash distance ${dHashDist}/64 — poor visual match`);

  // pHash reasoning
  if (pHashDist <= 8)
    reasons.push(`pHash distance ${pHashDist}/64 — near-identical frequency content`);
  else if (pHashDist <= 16)
    reasons.push(`pHash distance ${pHashDist}/64 — similar frequency content`);
  else reasons.push(`pHash distance ${pHashDist}/64 — different frequency content`);

  // Chain reasoning
  if (chainVerified) reasons.push(`On-chain receipt verified`);
  else reasons.push(`Chain verification unavailable or failed`);

  return { score: scoreValue, verdict, reasons };
}

/** Map a raw score to its band. Kept separate so tests can reuse it. */
export function verdictFor(value) {
  if (value >= BANDS.ATTRIBUTED) return 'ATTRIBUTED';
  if (value >= BANDS.PROBABLE) return 'PROBABLE';
  return 'INCONCLUSIVE';
}
