/**
 * ============================================================================
 *  OWNER: PERSON A  (deliverable A1)
 *  B and C: do not edit this file. Message A instead.
 * ============================================================================
 *
 * AES-256-GCM encrypt/decrypt + the two digests the registry needs.
 * Pure functions on Buffers — no DB, no network, no Express. Test it with
 * local files alone.
 *
 * GCM is chosen over CBC because it authenticates: if a ciphertext is tampered
 * with, decrypt() throws instead of returning garbage. That is a free integrity
 * check on every asset.
 *
 * Until these are real, the server substitutes server/core/fallback/crypto.js
 * (owner B) when ALLOW_CORE_FALLBACK=true. Delete that fallback at Hour 28.
 */

import { NOT_IMPLEMENTED } from './fallback/marker.js';

const IV_BYTES = 12; // 96-bit nonce — the GCM standard
const KEY_BYTES = 32; // AES-256
const TAG_BYTES = 16;

/**
 * @param {Buffer} buffer plaintext
 * @param {Buffer} key    32 bytes
 * @returns {{ ciphertext: Buffer, iv: Buffer, authTag: Buffer }}
 */
export function encrypt(buffer, key) {
  // TODO(A): crypto.randomBytes(IV_BYTES) -> createCipheriv('aes-256-gcm', key, iv)
  //          -> Buffer.concat([c.update(buffer), c.final()]) + c.getAuthTag()
  throw NOT_IMPLEMENTED('crypto.encrypt');
}

/**
 * @param {Buffer} ciphertext
 * @param {Buffer} key     32 bytes
 * @param {Buffer} iv      12 bytes
 * @param {Buffer} authTag 16 bytes
 * @returns {Buffer} plaintext — throws if the ciphertext was tampered with
 */
export function decrypt(ciphertext, key, iv, authTag) {
  // TODO(A): createDecipheriv('aes-256-gcm', key, iv) -> setAuthTag(authTag)
  throw NOT_IMPLEMENTED('crypto.decrypt');
}

/** @returns {Buffer} 32 bytes. The digest that goes on chain as contentSha. */
export function sha256(buffer) {
  // TODO(A): createHash('sha256').update(buffer).digest()
  throw NOT_IMPLEMENTED('crypto.sha256');
}

/**
 * @returns {Buffer} 16 bytes.
 * MD5 is here ONLY because the problem statement asks for a registry
 * fingerprint. It is never used for security. Say that out loud in the viva.
 */
export function md5(buffer) {
  // TODO(A): createHash('md5').update(buffer).digest()
  throw NOT_IMPLEMENTED('crypto.md5');
}

/**
 * scrypt key derivation — turns a human passphrase into a 32-byte AES key.
 * @returns {Buffer} 32 bytes
 */
export function deriveKey(passphrase, salt) {
  // TODO(A): scryptSync(passphrase, salt, KEY_BYTES, { N: 16384, r: 8, p: 1 })
  throw NOT_IMPLEMENTED('crypto.deriveKey');
}

export const constants = { IV_BYTES, KEY_BYTES, TAG_BYTES };
