/**
 * ============================================================================
 *  OWNER: PERSON A
 *  Everyone else: do not edit this file.
 * ============================================================================
 *
 * AES-256-GCM encrypt/decrypt + the two digests the registry needs.
 * Pure functions on Buffers — no DB, no network, no Express.
 *
 * GCM is chosen over CBC because it authenticates: if a ciphertext is tampered
 * with, decrypt() throws instead of returning garbage. That is a free integrity
 * check on every asset.
 */

import crypto from 'node:crypto';

const IV_BYTES = 12; // 96-bit nonce — the GCM standard
const KEY_BYTES = 32; // AES-256
const TAG_BYTES = 16;

/**
 * @param {Buffer} buffer plaintext
 * @param {Buffer} key    32 bytes
 * @returns {{ ciphertext: Buffer, iv: Buffer, authTag: Buffer }}
 */
export function encrypt(buffer, key) {
  const iv = crypto.randomBytes(IV_BYTES);
  const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
  const ciphertext = Buffer.concat([cipher.update(buffer), cipher.final()]);
  const authTag = cipher.getAuthTag();
  return { ciphertext, iv, authTag };
}

/**
 * @param {Buffer} ciphertext
 * @param {Buffer} key     32 bytes
 * @param {Buffer} iv      12 bytes
 * @param {Buffer} authTag 16 bytes
 * @returns {Buffer} plaintext — throws if the ciphertext was tampered with
 */
export function decrypt(ciphertext, key, iv, authTag) {
  const decipher = crypto.createDecipheriv('aes-256-gcm', key, iv);
  decipher.setAuthTag(authTag);
  return Buffer.concat([decipher.update(ciphertext), decipher.final()]);
}

/** @returns {Buffer} 32 bytes. The digest that goes on chain as contentSha. */
export function sha256(buffer) {
  return crypto.createHash('sha256').update(buffer).digest();
}

/**
 * @returns {Buffer} 16 bytes.
 * MD5 is here only because the specification asks for a registry fingerprint.
 * It is never relied on for security.
 */
export function md5(buffer) {
  return crypto.createHash('md5').update(buffer).digest();
}

/**
 * scrypt key derivation — turns a human passphrase into a 32-byte AES key.
 * @returns {Buffer} 32 bytes
 */
export function deriveKey(passphrase, salt) {
  return crypto.scryptSync(passphrase, salt, KEY_BYTES, { N: 16384, r: 8, p: 1 });
}

export const constants = { IV_BYTES, KEY_BYTES, TAG_BYTES };
