/**
 * ============================================================================
 *  OWNER: PERSON A
 *  Everyone else: do not edit this file.
 * ============================================================================
 *
 * Three perceptual hashes, 64 bits each. All three feed the BK-tree and are
 * OR-voted: if ANY one is within threshold the row stays a candidate. That is
 * what catches a photograph-of-a-screen leak, which pHash alone misses.
 *
 *   dHash | neighbour-pixel difference | PRIMARY — best at resize + compression
 *   pHash | DCT low frequencies        | strongest overall, second opinion
 *   aHash | average brightness         | cheap baseline, catches brightness shifts
 *
 * Return BigInt, not Number — 64 bits does not fit in a JS double.
 */

import { notImplemented } from '../lib/errors.js';

/**
 * @param {Buffer} imageBuffer
 * @returns {Promise<{ pHash: bigint, dHash: bigint, aHash: bigint }>}
 */
export async function hashes(imageBuffer) {
  // TODO(A): pHash  -> 32x32 grey -> DCT -> top-left 8x8 (skip DC) -> vs median
  //          dHash  -> 9x8 grey -> bit = px[x] > px[x+1]
  //          aHash  -> 8x8 grey -> bit = px > mean
  throw notImplemented('phash.hashes');
}

/**
 * Hamming distance between two 64-bit hashes.
 * @param {bigint} a
 * @param {bigint} b
 * @returns {number} 0..64
 */
export function hamming(a, b) {
  // TODO(A): popcount(a ^ b). Kernighan's trick: x &= x - 1n in a loop.
  throw notImplemented('phash.hamming');
}
