/**
 * ============================================================================
 *  OWNER: PERSON A  (deliverable A6)
 *  B and C: do not edit this file. Message A instead.
 * ============================================================================
 *
 * PSNR between the original and the marked buffer. This single number is the
 * entire "invisibility" claim, and C prints it under the before/after slider:
 *   "PSNR 42.7 dB — farak aankh se dikhta hi nahi"
 *
 *   MSE  = mean over all pixels/channels of (orig - marked)^2
 *   PSNR = 10 * log10(255^2 / MSE)
 *
 * Rules of thumb: >40 dB invisible · 35-40 dB fine · <30 dB the jury will see it.
 */

import { NOT_IMPLEMENTED } from './fallback/marker.js';

/**
 * @param {Buffer} originalBuffer
 * @param {Buffer} markedBuffer
 * @returns {Promise<number>} PSNR in dB (Infinity when the buffers are identical)
 */
export async function psnr(originalBuffer, markedBuffer) {
  // TODO(A): decode both to raw RGB at the same dimensions, then the formula above
  throw NOT_IMPLEMENTED('psnr.psnr');
}
