/**
 * ============================================================================
 *  OWNER: PERSON A
 *  Everyone else: do not edit this file.
 * ============================================================================
 *
 * PSNR between the original and the marked buffer — the whole "invisibility"
 * claim in one number, reported alongside every watermarked release.
 *
 *   MSE  = mean over all pixels/channels of (orig - marked)^2
 *   PSNR = 10 * log10(255^2 / MSE)
 *
 * Rules of thumb: >40 dB imperceptible · 35-40 dB acceptable · <30 dB visible.
 */

import { notImplemented } from '../lib/errors.js';

/**
 * @param {Buffer} originalBuffer
 * @param {Buffer} markedBuffer
 * @returns {Promise<number>} PSNR in dB (Infinity when the buffers are identical)
 */
export async function psnr(originalBuffer, markedBuffer) {
  // TODO(A): decode both to raw RGB at the same dimensions, then the formula above
  throw notImplemented('psnr.psnr');
}
