/**
 * ============================================================================
 *  OWNER: PERSON A  —  the core of the system.
 *  Everyone else: do not edit this file.
 * ============================================================================
 *
 * Haar DWT (2-level) -> QIM embed into the HL and LH sub-bands -> inverse DWT.
 * If the mark does not survive JPEG compression, nothing else in this repo
 * matters, so this is the module to get right first.
 *
 * ---------------------------------------------------------------------------
 * SUB-BAND CHOICE (already decided — just implement)
 *
 *   LL  -> don't touch, the mark becomes visible
 *   HH  -> don't touch, JPEG quantisation destroys it
 *   HL + LH -> the sweet spot   <-- YES
 * ---------------------------------------------------------------------------
 */

import sharp from 'sharp';
import crypto from 'node:crypto';
import { env } from '../lib/env.js';
import { psnr as computePsnr } from './psnr.js';
import { parsePayload } from './payload.js';

/** Whether extracted bits carry a valid CRC; malformed bits simply do not. */
function crcOf(bits) {
  try {
    return parsePayload(bits).crcOk;
  } catch {
    return false;
  }
}

/** How many scattered coefficients carry each bit (majority-voted on extract). */
export const REPEAT_FACTOR = 21;

// ========================== 1-D Haar Wavelet ===============================

function haar1D(a) {
  const n = a.length;
  const half = n >> 1;
  const low = new Float64Array(half);
  const high = new Float64Array(half);
  for (let i = 0; i < half; i++) {
    low[i] = (a[2 * i] + a[2 * i + 1]) / 2;
    high[i] = (a[2 * i] - a[2 * i + 1]) / 2;
  }
  return { low, high };
}

function ihaar1D(low, high) {
  const half = low.length;
  const out = new Float64Array(half * 2);
  for (let i = 0; i < half; i++) {
    out[2 * i] = low[i] + high[i];
    out[2 * i + 1] = low[i] - high[i];
  }
  return out;
}

// ========================== 2-D Haar Wavelet ===============================
// Apply to every row, then every column.
// Result quadrants:  LL | HL
//                    LH | HH

/**
 * Forward 2-D Haar on a w×h Float64Array (row-major).
 * Returns { data, w, h } where data has the quadrant layout above.
 */
function haar2D(pixels, w, h) {
  const out = new Float64Array(w * h);

  // Copy input to working buffer
  const buf = new Float64Array(pixels);

  const halfW = w >> 1;
  const halfH = h >> 1;

  // Rows: each row of length w → low (halfW) + high (halfW)
  const rowResult = new Float64Array(w * h);
  for (let y = 0; y < h; y++) {
    const row = buf.subarray(y * w, y * w + w);
    const { low, high } = haar1D(row);
    for (let x = 0; x < halfW; x++) {
      rowResult[y * w + x] = low[x]; // left half
      rowResult[y * w + halfW + x] = high[x]; // right half
    }
  }

  // Columns: each column of length h → low (halfH) + high (halfH)
  for (let x = 0; x < w; x++) {
    const col = new Float64Array(h);
    for (let y = 0; y < h; y++) col[y] = rowResult[y * w + x];
    const { low, high } = haar1D(col);
    for (let y = 0; y < halfH; y++) {
      out[y * w + x] = low[y]; // top half
      out[(halfH + y) * w + x] = high[y]; // bottom half
    }
  }

  return out;
}

/**
 * Inverse 2-D Haar.
 */
function ihaar2D(coeffs, w, h) {
  const halfW = w >> 1;
  const halfH = h >> 1;

  // Inverse columns first
  const colResult = new Float64Array(w * h);
  for (let x = 0; x < w; x++) {
    const low = new Float64Array(halfH);
    const high = new Float64Array(halfH);
    for (let y = 0; y < halfH; y++) {
      low[y] = coeffs[y * w + x];
      high[y] = coeffs[(halfH + y) * w + x];
    }
    const col = ihaar1D(low, high);
    for (let y = 0; y < h; y++) colResult[y * w + x] = col[y];
  }

  // Inverse rows
  const out = new Float64Array(w * h);
  for (let y = 0; y < h; y++) {
    const low = new Float64Array(halfW);
    const high = new Float64Array(halfW);
    for (let x = 0; x < halfW; x++) {
      low[x] = colResult[y * w + x];
      high[x] = colResult[y * w + halfW + x];
    }
    const row = ihaar1D(low, high);
    for (let x = 0; x < w; x++) out[y * w + x] = row[x];
  }

  return out;
}

// ========================== 2-Level DWT ====================================

/**
 * How deep the transform goes. The mark sits in the HL and LH bands of the
 * deepest level, one coefficient per BLOCK x BLOCK square of pixels.
 *
 * Level 3 (8x8 squares) rather than 2 (4x4): a leak is rarely the file
 * itself. A page shown fit-to-screen and screenshotted is shrunk to about
 * half size, and a messenger then re-saves it as a JPEG; detail on a
 * four-pixel scale does not survive both, detail on an eight-pixel one does.
 */
const LEVELS = 3;
const BLOCK = 1 << LEVELS;

/** Forward DWT, LEVELS deep: each level transforms the previous one's LL. */
function forwardDWT(pixels, w, h) {
  const coeffs = new Float64Array(pixels);
  for (let l = 0; l < LEVELS; l++) {
    const cw = w >> l;
    const ch = h >> l;
    const sub = new Float64Array(cw * ch);
    for (let y = 0; y < ch; y++) for (let x = 0; x < cw; x++) sub[y * cw + x] = coeffs[y * w + x];
    const t = haar2D(sub, cw, ch);
    for (let y = 0; y < ch; y++) for (let x = 0; x < cw; x++) coeffs[y * w + x] = t[y * cw + x];
  }
  return { coeffs };
}

/** Inverse of forwardDWT, deepest level first. */
function inverseDWT(coeffs, w, h) {
  const working = new Float64Array(coeffs);
  for (let l = LEVELS - 1; l >= 0; l--) {
    const cw = w >> l;
    const ch = h >> l;
    const sub = new Float64Array(cw * ch);
    for (let y = 0; y < ch; y++) for (let x = 0; x < cw; x++) sub[y * cw + x] = working[y * w + x];
    const t = ihaar2D(sub, cw, ch);
    for (let y = 0; y < ch; y++) for (let x = 0; x < cw; x++) working[y * w + x] = t[y * cw + x];
  }
  return working;
}

// ========================== Keyed Permutation ==============================

/**
 * Fisher-Yates shuffle seeded with HMAC-based PRNG.
 * Same seed + same n → same permutation on every machine.
 */
function keyedPermutation(n, seed) {
  const indices = Array.from({ length: n }, (_, i) => i);

  // Seeded PRNG: use HMAC-SHA256 to generate a stream of pseudo-random bytes
  let counter = 0;
  let byteBuf = Buffer.alloc(0);
  let bytePos = 0;

  function nextUint32() {
    if (bytePos + 4 > byteBuf.length) {
      byteBuf = crypto.createHmac('sha256', seed).update(`${counter++}`).digest();
      bytePos = 0;
    }
    const val = byteBuf.readUInt32LE(bytePos);
    bytePos += 4;
    return val;
  }

  // Fisher-Yates shuffle
  for (let i = n - 1; i > 0; i--) {
    const j = nextUint32() % (i + 1);
    [indices[i], indices[j]] = [indices[j], indices[i]];
  }
  return indices;
}

// ========================== QIM ============================================

/**
 * Move the coefficient to the NEAREST point of the bit's lattice — up or down,
 * at most half a step. Always moving up within the current cell (the old
 * rule) pushed a flat white page past 255, where the change was clipped off
 * and the mark did not survive a JPEG. extractBit reads both the same way.
 */
function embedBit(c, bit, delta) {
  const offset = bit === 0 ? 0.25 : 0.75;
  return delta * (Math.round(c / delta - offset) + offset);
}

function extractBit(c, delta) {
  const r = (((c % delta) + delta) % delta) / delta;
  return r < 0.5 ? 0 : 1;
}

// ========================== Collect embeddable coefficient indices ==========

/**
 * Indices into the coefficient array of the deepest level's HL and LH bands.
 * The finer levels are left alone: JPEG quantisation and any rescaling
 * destroy them first.
 */
function getEmbeddableIndices(w, h) {
  const lw = w >> LEVELS; // width of the deepest LL, and of each of its bands
  const lh = h >> LEVELS;
  const indices = [];
  // HL: rows [0, lh), cols [lw, 2*lw)
  for (let y = 0; y < lh; y++) for (let x = lw; x < 2 * lw; x++) indices.push(y * w + x);
  // LH: rows [lh, 2*lh), cols [0, lw)
  for (let y = lh; y < 2 * lh; y++) for (let x = 0; x < lw; x++) indices.push(y * w + x);
  return indices;
}

// ========================== Pad to power-of-2 multiples of 4 ===============

/** Round up to whole BLOCKs, so every level halves evenly. */
function padToBlock(n) {
  return Math.ceil(n / BLOCK) * BLOCK;
}

// ========================== RGB ↔ Y channel ================================

function rgbToY(raw, w, h) {
  const y = new Float64Array(w * h);
  for (let i = 0; i < w * h; i++) {
    y[i] = 0.299 * raw[i * 3] + 0.587 * raw[i * 3 + 1] + 0.114 * raw[i * 3 + 2];
  }
  return y;
}

// ========================== EXPORTED FUNCTIONS =============================

/**
 * @param {Buffer} imageBuffer  original image bytes
 * @param {string} payloadBits  exactly 48 chars of '0'/'1' (see core/payload.js)
 * @param {number} delta        QIM strength, default 12
 * @returns {Promise<{ buffer: Buffer, psnrDb: number, deltaUsed: number }>}
 */
export async function embed(imageBuffer, payloadBits, delta = 12) {
  const seed = env.watermarkSeed;
  const numBits = payloadBits.length; // 48

  // 1. Decode image to raw RGB
  const meta = await sharp(imageBuffer).metadata();
  const origW = meta.width;
  const origH = meta.height;
  const paddedW = padToBlock(origW);
  const paddedH = padToBlock(origH);

  const rawRGB = await sharp(imageBuffer)
    .removeAlpha()
    .toColourspace('srgb')
    // Repeat the edge pixels out to the padded size. Resizing instead would
    // resample the whole page by a pixel or two, blurring every text edge.
    .extend({ right: paddedW - meta.width, bottom: paddedH - meta.height, extendWith: 'copy' })
    .raw()
    .toBuffer();

  // 2. Extract Y channel
  const yChannel = rgbToY(rawRGB, paddedW, paddedH);

  // 3. 2-level forward DWT
  const dwt = forwardDWT(yChannel, paddedW, paddedH);
  const coeffs = dwt.coeffs;

  // 4. Get embeddable HL+LH indices and apply keyed permutation
  const rawIndices = getEmbeddableIndices(paddedW, paddedH);
  const perm = keyedPermutation(rawIndices.length, seed);
  const permutedIndices = perm.map((i) => rawIndices[i]);

  // 5. Embed: each bit spread across REPEAT_FACTOR scattered positions
  for (let b = 0; b < numBits; b++) {
    const bit = parseInt(payloadBits[b], 10);
    for (let r = 0; r < REPEAT_FACTOR; r++) {
      const idx = permutedIndices[(b * REPEAT_FACTOR + r) % permutedIndices.length];
      coeffs[idx] = embedBit(coeffs[idx], bit, delta);
    }
  }

  // 6. Inverse 2-level DWT → modified Y channel
  const reconstructedY = inverseDWT(coeffs, paddedW, paddedH);

  // 7. Apply the Y delta back to the original RGB pixels
  const markedRGB = Buffer.from(rawRGB);
  for (let i = 0; i < paddedW * paddedH; i++) {
    const yDelta = reconstructedY[i] - yChannel[i];
    for (let c = 0; c < 3; c++) {
      const idx = i * 3 + c;
      markedRGB[idx] = Math.max(0, Math.min(255, Math.round(rawRGB[idx] + yDelta)));
    }
  }

  // 8. Re-encode as PNG
  const markedBuffer = await sharp(markedRGB, {
    raw: { width: paddedW, height: paddedH, channels: 3 },
  })
    // Cut the padding back off: the page itself is never resampled.
    .extract({ left: 0, top: 0, width: origW, height: origH })
    .png()
    .toBuffer();

  // 9. Compute PSNR
  const psnrDb = await computePsnr(imageBuffer, markedBuffer);

  return { buffer: markedBuffer, psnrDb, deltaUsed: delta };
}

/**
 * @param {Buffer} imageBuffer  possibly attacked/compressed image
 * @param {number} delta        QIM strength used during embed (default 12)
 * @returns {Promise<{ payloadBits: string, bitConfidence: number, eccCorrected: boolean }>}
 *          bitConfidence in [0,1] — fraction of bits recovered with agreement
 */
/**
 * Extract 48 bits from an image at a single fixed orientation.
 */
async function extractSingle(imageBuffer, delta = 12) {
  const seed = env.watermarkSeed;
  const numBits = 48;

  // 1. Decode image
  const meta = await sharp(imageBuffer).metadata();
  const origW = meta.width;
  const origH = meta.height;
  const paddedW = padToBlock(origW);
  const paddedH = padToBlock(origH);

  const rawRGB = await sharp(imageBuffer)
    .removeAlpha()
    .toColourspace('srgb')
    // Repeat the edge pixels out to the padded size. Resizing instead would
    // resample the whole page by a pixel or two, blurring every text edge.
    .extend({ right: paddedW - meta.width, bottom: paddedH - meta.height, extendWith: 'copy' })
    .raw()
    .toBuffer();

  // 2. Extract Y channel
  const yChannel = rgbToY(rawRGB, paddedW, paddedH);

  // 3. 2-level forward DWT
  const dwt = forwardDWT(yChannel, paddedW, paddedH);
  const coeffs = dwt.coeffs;

  // 4. Same keyed permutation as embed
  const rawIndices = getEmbeddableIndices(paddedW, paddedH);
  const perm = keyedPermutation(rawIndices.length, seed);
  const permutedIndices = perm.map((i) => rawIndices[i]);

  // 5. Extract: read REPEAT_FACTOR copies, majority vote
  const bits = [];
  let totalAgreement = 0;

  for (let b = 0; b < numBits; b++) {
    let votes = 0;
    for (let r = 0; r < REPEAT_FACTOR; r++) {
      const idx = permutedIndices[(b * REPEAT_FACTOR + r) % permutedIndices.length];
      votes += extractBit(coeffs[idx], delta);
    }
    const majorityBit = votes > REPEAT_FACTOR / 2 ? 1 : 0;
    const agreement = Math.max(votes, REPEAT_FACTOR - votes) / REPEAT_FACTOR;
    totalAgreement += agreement;
    bits.push(majorityBit);
  }

  let payloadBits = bits.join('');
  const bitConfidence = totalAgreement / numBits;

  // 6. Attempt ECC decode
  let eccCorrected = false;
  try {
    const { rsDecode } = await import('./ecc.js');
    const decoded = rsDecode(payloadBits);
    if (decoded.corrected && decoded.bits) {
      eccCorrected = true;
      payloadBits = decoded.bits;
    }
  } catch {
    // ECC not available
  }

  return { payloadBits, bitConfidence, eccCorrected, rotationAngle: 0 };
}

/**
 * Read the 48 bits from only the part of the page a capture actually shows.
 *
 * A screenshot or photo of a tall document usually holds just the part that
 * was on screen. Once that part has been put back where it belongs on a
 * canvas the size of the released copy, every coefficient outside it would
 * read as noise — so only positions whose 4x4 pixel block lies inside
 * `visible` get a vote. Each bit is spread over REPEAT_FACTOR positions
 * scattered across the page, so a partial view still carries most of them.
 *
 * @param {Buffer} imageBuffer  aligned to the released copy's size
 * @param {number} delta        the QIM step that release was marked with
 * @param {{x0:number,y0:number,x1:number,y1:number}|null} visible
 *        the captured region, in the image's own pixels; null = all of it
 * @returns {Promise<{ payloadBits: string, bitConfidence: number, eccCorrected: boolean, votes: number }>}
 */
export async function extractVisible(imageBuffer, delta = 12, visible = null) {
  const seed = env.watermarkSeed;
  const numBits = 48;

  const meta = await sharp(imageBuffer).metadata();
  const paddedW = padToBlock(meta.width);
  const paddedH = padToBlock(meta.height);
  const rawRGB = await sharp(imageBuffer)
    .removeAlpha()
    .toColourspace('srgb')
    // Repeat the edge pixels out to the padded size. Resizing instead would
    // resample the whole page by a pixel or two, blurring every text edge.
    .extend({ right: paddedW - meta.width, bottom: paddedH - meta.height, extendWith: 'copy' })
    .raw()
    .toBuffer();

  const { coeffs } = forwardDWT(rgbToY(rawRGB, paddedW, paddedH), paddedW, paddedH);
  const rawIndices = getEmbeddableIndices(paddedW, paddedH);
  const perm = keyedPermutation(rawIndices.length, seed);
  const permutedIndices = perm.map((i) => rawIndices[i]);

  // The visible rectangle in padded pixels.
  const sx = paddedW / meta.width;
  const sy = paddedH / meta.height;
  const box = visible
    ? {
        x0: visible.x0 * sx,
        y0: visible.y0 * sy,
        x1: visible.x1 * sx,
        y1: visible.y1 * sy,
      }
    : null;
  const lw = paddedW >> LEVELS;
  const lh = paddedH >> LEVELS;
  const inView = (idx) => {
    if (!box) return true;
    const y = Math.floor(idx / paddedW);
    const x = idx % paddedW;
    // HL sits right of the deepest LL block, LH below it; either way one
    // coefficient summarises one BLOCK x BLOCK square of pixels.
    const bx = y < lh ? x - lw : x;
    const by = y < lh ? y : y - lh;
    return (
      bx * BLOCK >= box.x0 &&
      by * BLOCK >= box.y0 &&
      bx * BLOCK + BLOCK <= box.x1 &&
      by * BLOCK + BLOCK <= box.y1
    );
  };

  const bits = [];
  let totalAgreement = 0;
  let votesUsed = 0;
  for (let b = 0; b < numBits; b++) {
    let ones = 0;
    let n = 0;
    for (let r = 0; r < REPEAT_FACTOR; r++) {
      const idx = permutedIndices[(b * REPEAT_FACTOR + r) % permutedIndices.length];
      if (!inView(idx)) continue;
      ones += extractBit(coeffs[idx], delta);
      n++;
    }
    votesUsed += n;
    bits.push(n && ones > n / 2 ? 1 : 0);
    totalAgreement += n ? Math.max(ones, n - ones) / n : 0.5;
  }

  let payloadBits = bits.join('');
  let eccCorrected = false;
  try {
    const { rsDecode } = await import('./ecc.js');
    const decoded = rsDecode(payloadBits);
    if (decoded.corrected && decoded.bits) {
      eccCorrected = true;
      payloadBits = decoded.bits;
    }
  } catch {
    // ECC not available
  }
  return { payloadBits, bitConfidence: totalAgreement / numBits, eccCorrected, votes: votesUsed };
}

/**
 * @param {Buffer} imageBuffer  possibly attacked/compressed/rotated image
 * @param {number} delta        QIM strength used during embed (default 12)
 * @param {{ multiOrientation?: boolean }} options
 * @returns {Promise<{ payloadBits: string, bitConfidence: number, eccCorrected: boolean, rotationAngle?: number }>}
 *          bitConfidence in [0,1] — fraction of bits recovered with agreement
 */
export async function extract(imageBuffer, delta = 12, { multiOrientation = true } = {}) {
  // Fast path: attempt standard 0° orientation
  const baseResult = await extractSingle(imageBuffer, delta);

  const crcOk = crcOf(baseResult.payloadBits);

  // If CRC is valid or orientation check is disabled, return immediately
  if (crcOk || !multiOrientation) {
    return baseResult;
  }

  // Multi-orientation scan (90°, 180°, 270°) to catch rotated leaks / smartphone photos
  const angles = [90, 180, 270];
  let bestResult = baseResult;

  for (const angle of angles) {
    try {
      const rotated = await sharp(imageBuffer).rotate(angle).png().toBuffer();
      const candidate = await extractSingle(rotated, delta);
      candidate.rotationAngle = angle;

      if (crcOf(candidate.payloadBits)) {
        return candidate; // Exact match found on rotation
      }

      if (candidate.bitConfidence > bestResult.bitConfidence) {
        bestResult = candidate;
      }
    } catch {
      // Rotation attempt skipped
    }
  }

  return bestResult;
}
