/**
 * ============================================================================
 *  OWNER: PERSON A  —  the core of the system.
 *  Everyone else: do not edit this file.
 * ============================================================================
 *
 * Haar DWT (2-level) -> QIM embed into the HL and LH sub-bands -> inverse DWT.
 * If the mark does not survive JPEG compression, nothing else in this repo
 * matters, so this is the module to get right first.
 *
 * ---------------------------------------------------------------------------
 * SUB-BAND CHOICE (already decided — just implement)
 *
 *   LL  -> don't touch, the mark becomes visible
 *   HH  -> don't touch, JPEG quantisation destroys it
 *   HL + LH -> the sweet spot   <-- YES
 *
 * ---------------------------------------------------------------------------
 * THE TRANSFORM — the entire 1-D Haar wavelet
 *
 *   function haar1D(a) {
 *     const n = a.length, half = n >> 1;
 *     const low = new Float64Array(half), high = new Float64Array(half);
 *     for (let i = 0; i < half; i++) {
 *       low[i]  = (a[2*i] + a[2*i+1]) / 2;   // average    -> low frequency
 *       high[i] = (a[2*i] - a[2*i+1]) / 2;   // difference -> high frequency
 *     }
 *     return { low, high };
 *   }
 *   // 2-D = apply to every row, then to every column.
 *   // Result quadrants:  LL | HL
 *   //                    LH | HH
 *
 * ---------------------------------------------------------------------------
 * BIT EMBEDDING — QIM (Quantisation Index Modulation)
 *
 *   function embedBit(c, bit) {
 *     const q = Math.floor(c / DELTA);
 *     return DELTA * (q + (bit === 0 ? 0.25 : 0.75));
 *   }
 *   function extractBit(c) {
 *     const r = ((c % DELTA) + DELTA) % DELTA / DELTA;
 *     return r < 0.5 ? 0 : 1;
 *   }
 *
 *   DELTA  4  -> invisible but fragile
 *   DELTA 24  -> survives everything but faintly visible
 *   DELTA 8-16 -> sweet spot. MEASURE, DON'T GUESS.
 *
 * ---------------------------------------------------------------------------
 * COEFFICIENT SELECTION — the part that survives a crop
 *
 * Do NOT embed into the first N coefficients in raster order; one crop kills
 * them all. Use a KEYED PSEUDO-RANDOM PERMUTATION of the HL/LH coefficient
 * indices (seed = WATERMARK_SEED from .env, identical on every machine) and
 * spread each bit across 5 scattered positions. Majority-vote on extraction.
 * This is what makes 20% crop survivable — 41/48 bits in the target table.
 * ---------------------------------------------------------------------------
 */

import { notImplemented } from '../lib/errors.js';

/** How many scattered coefficients carry each bit (majority-voted on extract). */
export const REPEAT_FACTOR = 5;

/**
 * @param {Buffer} imageBuffer  original image bytes
 * @param {string} payloadBits  exactly 48 chars of '0'/'1' (see core/payload.js)
 * @param {number} delta        QIM strength, default 12
 * @returns {Promise<{ buffer: Buffer, psnrDb: number, deltaUsed: number }>}
 */
export async function embed(imageBuffer, payloadBits, delta = 12) {
  // TODO(A): decode (sharp, Jimp fallback) -> Y channel -> 2-level Haar DWT
  //          -> keyed permutation of HL+LH indices -> QIM 48 bits x 5 repeats
  //          -> inverse DWT -> re-encode -> psnr(original, marked)
  throw notImplemented('watermark.embed');
}

/**
 * @param {Buffer} imageBuffer  possibly attacked/compressed image
 * @returns {Promise<{ payloadBits: string, bitConfidence: number, eccCorrected: boolean }>}
 *          bitConfidence in [0,1] — fraction of bits recovered with agreement
 */
export async function extract(imageBuffer) {
  // TODO(A): same decode + DWT + permutation -> read 5 copies of each bit ->
  //          majority vote -> bitConfidence = mean vote margin -> ecc.rsDecode
  throw notImplemented('watermark.extract');
}
